#!/usr/bin/python3

"""
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

"""
Explanation:

Every even number in the fibonacci sequence is also
every third number (starting with 2).

    1, (2), 3, 5, (8), 13, 21, (34), ...
    ------     ------      --------

Only the number before the even number (left) and the even number (right)
need to be calculated.
"""

MAX = 4000000


def main():
    total = 0
    left = 1
    right = 2
    while(right < MAX):
        total += right
        temp_l = left + 2 * right
        temp_r = 2 * left + 3 * right
        left = temp_l
        right = temp_r
    print(total)


if __name__ == "__main__":
    main()
